media:
  input: static/media
  output: /media

content:
  - name: works
    label: 'Works'
    type: collection
    view:
      fields: [title, has_model]
      primary: title
      sort: [title, has_model]
      default:
        search: ''
        sort: title
        order: asc
    path: 'src/lib/db/works'
    fields:
      - name: title
        label: 'Title'
        type: string
        required: true
      - name: image
        label: 'Image'
        type: image
        options:
          path: static/media/images
          input: static/media/images
          output: /media/images
        required: true
      - name: year
        label: Year
        type: string
        required: false
      - name: description
        label: 'Description'
        type: rich-text
        required: false
        options:
          format: html

      - name: tags
        label: Tags
        type: select
        required: false
        options:
          multiple: true
          values:
            [
              { value: 3d, label: '3D' },
              { value: print, label: 'Print' },
              { value: sculpture, label: 'Sculpture' },
              { value: paint, label: 'Paint' },
              { value: pen, label: 'Pen' },
              { value: graphic, label: 'Graphic' },
              { value: screenprinting, label: 'Screenprinting' },
              { value: etching, label: 'Etching' },
              { value: linocut, label: 'Linocut' },
              { value: digital, label: 'Digital' },
              { value: extra, label: 'Extra' },
              { value: illustration, label: 'Illustration' },
              { value: mixed_media, label: 'Mixed Media' },
              { value: gsplat, label: 'Gsplat' },
              { value: ink, label: 'Ink' }
            ]
      - name: has_model
        label: '3D Model'
        type: boolean
        default: false
      - name: model_format
        label: 'Model Format'
        type: select
        required: false
        default: 'null'
        options:
          values:
            [
              { value: glb, label: '.glb' },
              { value: gltf, label: '.gltf' },
              { value: splat, label: '.splat' },
              { value: ply, label: '.ply' },
              { value: 'null', label: 'No Model'}
            ]
      - name: model_file
        label: 'Model File'
        type: file
        required: false
        options:
          path: static/media/models
          input: static/media/models
          output: /media/models
          extensions: [glb, gltf, splat, ply]

  - name: about
    label: 'About'
    type: file
    path: 'src/lib/db/about.json'
    format: json
    icon: user
    fields:
      - name: bio
        label: 'Biography'
        type: rich-text
        required: true
        options:
          format: html
      - name: email
        label: 'Email'
        type: string
        pattern:
          regex: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
          message: 'Please enter a valid email address'
      - name: location
        label: 'Location'
        type: string
      - name: avatar
        label: 'About Avatar'
        type: image
        required: true
      - name: bg_image
        label: 'Background Image'
        type: image
        required: false
      - name: social
        label: 'Social Links'
        type: object
        list: true
        required: false
        fields:
          - name: platform
            label: 'Platform'
            type: select
            options:
              values: [Instagram, Twitter, LinkedIn, GitHub, Behance, ArtStation]
            required: true
          - name: url
            label: 'URL'
            type: string
            pattern:
              regex: '^https?:\/\/.*$'
              message: 'Must be a valid URL starting with http:// or https://'
            required: true
      - name: cv
        label: 'CV/Resume'
        type: object
        required: false
        fields:
          - name: education
            label: 'Education'
            type: object
            list: true
            required: false
            fields:
              - name: institution
                label: 'Institution'
                type: string
                required: true
              - name: degree
                label: 'Degree'
                type: string
                required: true
              - name: year
                label: 'Year'
                type: string
          - name: exhibitions
            label: 'Exhibitions'
            type: object
            list: true
            required: false
            fields:
              - name: title
                label: 'Exhibition Title'
                type: string
                required: true
              - name: venue
                label: 'Venue'
                type: string
                required: true
              - name: year
                label: 'Year'
                type: string
                required: true
              - name: description
                label: 'Description'
                type: text
                required: false
  - name: global
    label: 'Global'
    type: file
    path: 'src/lib/db/global.json'
    format: json
    fields:
      - name: title
        label: 'Site Title'
        type: string
        required: true
        default: 'Zebra Portfolio'
      - name: description
        label: 'Site Description'
        type: string
        required: false
      - name: keywords
        label: 'Site Keywords'
        type: string
        required: false
      - name: logo
        label: 'Site Logo'
        type: image
        required: false
      - name: filter_bg
        label: 'Filter Section Background'
        type: image
        required: false
      - name: logo_3d
        label: '3D Info Logo'
        type: image
        required: false
